options:
    # paired for single-end reads
    paired: True

# path of the file with sample list
samples: '/DATA/projects/j.bhin/organoid-GC/RNAseq/test.tsv'


################################################################################
# Path configuration                                                           
################################################################################

path:
  data: '/DATA/projects/j.bhin/organoid-GC/RNAseq'
  pipeline: '/home/j.bhin/pipelines/STAR-Fusion'


star_fusion:
  reflib: /DATA/projects/fgfr2/cell-lines/fusions/GRCh38_v27_CTAT_lib_Feb092018/ctat_genome_lib_build_dir
  threads: 8
  options:
    - --FusionInspector validate
    - --denovo_reconstruct
    - --examine_coding_effect
